#!/bin/bash

# Just a script to do whats here https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

KEY_RING_ORIGIN="https://packages.cloud.google.com/apt/doc/apt-key.gpg"
KEY_RING="/etc/apt/keyrings/kubernetes-archive-keyring.gpg"
REPO="https://apt.kubernetes.io/ kubernetes-xenial main"
REPO_CONF="/etc/apt/sources.list.d/kubernetes.list"
PACKAGES="kubelet kubeadm kubectl"

apt-get update
apt-get install -y apt-transport-https ca-certificates curl

# Get gpg key
echo "Getting key from $KEY_RING_ORIGIN$"
curl -fsSLo $KEY_RING $KEY_RING_ORIGIN
 

# Add repo
echo "deb [signed-by=$KEY_RING] $REPO | sudo tee $REPO_CONF

# Install and mark
apt update
apt-get install $PACKAGES
apt-mark hold $PACKAGES
